### ISSUE TITLE
Test a basic complete request/response

### ISSUE THREAD

**Issue by dionyziz** [okTurtles/pydnschain#13]
We should add a test that does the following:
1. Makes a request to `id/dionyziz` (or some other entry that we know will be valid and contain some prespecified data)
2. Checks that the response is valid JSON
3. Checks that the response contains the key `email`
4. Checks that its value is `dionyziz@gmail.com` (or some other known value we don't expect to change)

**Comment by dionyziz** [comment]
There's already a basic functionality demo here:

https://github.com/okTurtles/pydnschain/blob/master/dnschain/server.py#L72

Let's move this to a unit test.

**Comment by taoeffect** [comment]
Alright, so travis support has been added, but someone (@dionyziz ? @charapod?) needs to update the [`.travis.yml`](https://github.com/okTurtles/pydnschain/blob/master/.travis.yml) file so that the correct command gets run to do the actual tests. You just need to update the `script:` key value with the right command, and perhaps (if necessary) uncomment and correctly set the value for the `install:` key (if necessary).

**Comment by dionyziz** [comment]
In #16

**Comment by dionyziz** [comment]
@charapod can you confirm if this is done?

**Comment by charapod** [comment]
I think it' s already confirmed and merged @dionyziz ! Am I right?

**Comment by dionyziz** [comment]
Sounds like it, just wanted to make sure. Thanks!
