### ISSUE TITLE
Zancas needs to learn the OKTurtles way of reviewing code

### ISSUE THREAD

**Issue by zancas** [okTurtles/pydnschain#7]
@dionyziz said:  (This is me paraphrasing) "Don't close a PR that is opened against your own code, let a reviewer close the PR when they merge your code into the production/master branch."

OK, I understand the policy.

The work flow I was familiar with went like this:
1.  Open an issue on the github repo describing the feature requested, or the bug to be fixed.
2.  Once the issue has been opened that creates an issue number.
3.  Use the issue number mentioned in "1." to name a new branch according to the following format:
       $ISSUE_NUMBER-$DESCRIPTION-OF-BUG-OR-FEATURE_$NUMBER_OF_TIMES_REBASED
4.  Hack along on the issue branch, until one of several things happens:
        1.  production/master is ahead of the branch in a substantive way
        2.  the branch needs to have a cleaner set of commits
5. Create a new branch that's never been shared before that has the same name as the previous branch, but with the $NUMBER_OF_TIMES_REBASED incremented.   Then rebase that new branch on top of production/master.    _Then_ push that branch to a shared repository.  This has nice features:
   1.  The original development history remains (under original branch name, and is never rebased)
   2.  There's never moment when developers working on the same branch are faced with a skewed history, because NO _SHARED_ BRANCH IS EVER REBASED.
   3.  (Maybe not a feature.)  There're no merge commits, when the branch to be merged to master is finally passing review, the merge process (not strictly guaranteed) will be "fast forward" merge.

What do you think?   If I were to follow that scheme, then I'd create a new branch, rebase it on master, squash it to a nice set of intelligible commits, and _then_ push it to github, and open a pull request against it.

I guess this flow terminates when a pull request is successfully merged which should only happen against the last, cleaned up, review-passing branch.

**Comment by taoeffect** [comment]
I think it depends on the number of people who might be stepping on each other's feet.

The scheme you've described above, while nifty, I think might confuse/scare git newbs. It did confuse me a bit. :P

I think the advice @dionyziz gave was simple and good advice: I had opened a new PR against the new branch you created so that I could review your changes. That's all. I'm going to go do that review now actually, and when I think your code is ready to be merged I'll close the PR, and you can open one yourself so that GH doesn't get confused and properly shows who is responsible for the PR.

OK to close this issue? Feel free to re-open it if you think I haven't adequately addressed your question. Better yet might be to hash it out on Slack. This project is too small for any complicated schemes. :)
